name: simple_dart_context_menu
description: Context Menu Component
version: 0.0.3
repository: https://github.com/simple-dart/context_menu
platforms:
  web:

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  simple_dart_label: ^0.0.1
  simple_dart_modal_controller: ^0.0.7
  simple_dart_ui_core: ^0.0.3
